
services:
  backend:
    container_name: backend
    depends_on:
      database:
        condition: service_healthy
    entrypoint: [ "./entrypoint.sh" ]
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    env_file:
      - .env
    restart: always

  frontend:
    container_name: frontend
    depends_on:
      - backend
    entrypoint: [ "./entrypoint.sh" ]
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: always

  database:
    container_name: database
    image: postgres:18.1-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "fermi"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s


volumes:
  postgres-data:
    driver: local