# Generated by Django 6.0.3 on 2026-04-04 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog', models.CharField(choices=[('fermi_4fgl', 'Fermi 4FGL'), ('hawc', 'HAWC'), ('lhaaso', 'LHAASO'), ('tevcat', 'TeVCat'), ('ned', 'NED')], db_index=True, max_length=32)),
                ('source_name', models.CharField(db_index=True, max_length=256)),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('pos_err_deg', models.FloatField(blank=True, null=True)),
                ('healpix_id', models.BigIntegerField(db_index=True)),
                ('flux', models.FloatField(blank=True, null=True)),
                ('flux_err', models.FloatField(blank=True, null=True)),
                ('flux_unit', models.CharField(blank=True, max_length=32)),
                ('energy_min_gev', models.FloatField(blank=True, null=True)),
                ('energy_max_gev', models.FloatField(blank=True, null=True)),
                ('spectral_index', models.FloatField(blank=True, null=True)),
                ('source_class', models.CharField(blank=True, max_length=128)),
                ('extra', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['healpix_id'], name='fermi_catal_healpix_e1896f_idx'), models.Index(fields=['catalog', 'healpix_id'], name='fermi_catal_catalog_89da96_idx')],
                'unique_together': {('catalog', 'source_name')},
            },
        ),
        migrations.CreateModel(
            name='CrossMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('separation_deg', models.FloatField()),
                ('method', models.CharField(choices=[('name', 'Matched by name'), ('position', 'Matched by position')], max_length=16)),
                ('confidence', models.FloatField(default=1.0)),
                ('source_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossmatches_as_a', to='fermi.catalogsource')),
                ('source_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossmatches_as_b', to='fermi.catalogsource')),
            ],
            options={
                'indexes': [models.Index(fields=['source_a'], name='fermi_cross_source__842400_idx'), models.Index(fields=['source_b'], name='fermi_cross_source__66b62f_idx')],
                'unique_together': {('source_a', 'source_b')},
            },
        ),
    ]
