# Generated by Django 6.0.4 on 2026-04-26 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="catalogentry",
            new_name="sources_cat_catalog_b3a729_idx",
            old_name="sources_cat_catalog_name_idx",
        ),
        migrations.RenameIndex(
            model_name="catalogentry",
            new_name="sources_cat_source__d42df2_idx",
            old_name="sources_cat_source_id_idx",
        ),
        migrations.RenameIndex(
            model_name="source",
            new_name="sources_sou_ra_02404a_idx",
            old_name="sources_sou_ra_dec_idx",
        ),
        migrations.RenameIndex(
            model_name="source",
            new_name="sources_sou_primary_024e3b_idx",
            old_name="sources_sou_primary_catalog_idx",
        ),
    ]
