# Generated by Django 6.0.4 on 2026-05-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sources",
            "0002_rename_sources_cat_catalog_name_idx_sources_cat_catalog_b3a729_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogentry",
            name="magic_calculated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of MAGIC simulation calculation",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="catalogentry",
            name="magic_detectable",
            field=models.BooleanField(
                default=False,
                help_text="MAGIC simulation: source detectable with criteria (sigma≥5)",
            ),
        ),
        migrations.AddField(
            model_name="catalogentry",
            name="magic_params_hash",
            field=models.CharField(
                blank=True,
                help_text="Hash of observation parameters used for MAGIC calculation",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="catalogentry",
            name="magic_significance",
            field=models.FloatField(
                blank=True,
                help_text="MAGIC simulation: overall Li&Ma significance [sigma]",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="catalogentry",
            index=models.Index(
                fields=["magic_significance"], name="sources_cat_magic_s_2a9994_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="catalogentry",
            index=models.Index(
                fields=["magic_detectable"], name="sources_cat_magic_d_127a09_idx"
            ),
        ),
    ]
