# Generated by Django 6.0.4 on 2026-05-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0003_catalogentry_magic_calculated_at_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="catalogentry",
            name="sources_cat_magic_s_2a9994_idx",
        ),
        migrations.RemoveIndex(
            model_name="catalogentry",
            name="sources_cat_magic_d_127a09_idx",
        ),
        migrations.AlterField(
            model_name="catalogentry",
            name="magic_detectable",
            field=models.BooleanField(
                blank=True,
                help_text="MAGIC simulation: source detectable with criteria (sigma≥5). None if not calculated.",
                null=True,
            ),
        ),
    ]
